### ISSUE TITLE
kong ingress controller 설정 후 기본 값 요청드립니다.

### ISSUE THREAD

**Issue by subicura** [k8s-study/kong#6]
anonymous key auth credential 설정입니다.

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth-plugin
---

apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: anonymous-consumer
username: anonymous
---

apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: anonymous-credential
consumerRef: anonymous-consumer
type: key-auth
config:
  key: anonymous
```
